### ISSUE TITLE
Add region/culture for Asia, Latin America, and Oceania, and update artwork to be SVG

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/soccer-common#10]

**Comment by Luisav1** [comment]
All the images are updated and ready for your review @amanda-phet.

**Comment by amanda-phet** [comment]
The people look great to me! 

One last update and I think this is done. Here are the svg soccer balls. 

![ballDark](https://github.com/phetsims/soccer-common/assets/7852916/b5870332-a596-4273-9a04-259f8d4679b9)
![ball](https://github.com/phetsims/soccer-common/assets/7852916/d01a1561-a71c-4faa-97d9-b8e8f5122889)

**Comment by Luisav1** [comment]
The soccer ball is updated and it's looking good! It's ready for your review @amanda-phet.

**Comment by amanda-phet** [comment]
Thanks, I agree it looks good!
