### ISSUE TITLE
webgl flag is disturbing SVG rendering of kickers

### ISSUE THREAD

**Issue by marlitas** [phetsims/soccer-common#11]
In order to fix https://github.com/phetsims/center-and-variability/issues/91, we added the option `renderer: 'webgl'` to `KickerNode` in soccer-common. Now that we are wanting to use SVG artwork instead of PNG setting the renderer to `webgl` is removing SVG's ability to be able to expand and contract with no quality loss. After testing for the bug in FireFox with the new SVG images I was unable to reproduce the flicker.

Once all images have been converted to SVG, I would like QA to confirm that the flicker is indeed gone and we are safe to remove that flag.

**Comment by marlitas** [comment]
We have converted all of the kickers to svg files and are ready to test if the flashing is still occurring in firefox. @Nancy-Salpepi and/or @KatieWoe I tested in firefox and didn't see anything on my end, but would love a confirmation by QA. 

I followed the reproduction steps in https://github.com/phetsims/center-and-variability/issues/91

Thanks!

**Comment by Nancy-Salpepi** [comment]
Looks good to me on mac + FF and Win10 + FF!

**Comment by marlitas** [comment]
Awesome. Thank you. FYI @amanda-phet. I'm going to go ahead and close.
