### ISSUE TITLE
Re-number some image files related to kickers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/soccer-common#12]
@amanda-phet and I discussed this.  Some of the image files are not numbered to match the kicker that they correspond to. 

For 'africa', see KickerPortrayalAfrica. 
- [x] player05 => player11
- [x] player06 => player07
- [x] player07 => player13

For 'africaModest', see KickerPortrayalAfricaModest.
- [x] player01 => player03
- [x] player02 => player06
- [x] variabilityPlayer01 => variabilityPlayer02

I'll adjust these.

**Comment by pixelzoom** [comment]
This is done. @amanda-phet please review. Close if OK.

**Comment by amanda-phet** [comment]
Look good.
