### ISSUE TITLE
'usa' image files are displayed very small.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/soccer-common#13]
While working on renaming localized image files for https://github.com/phetsims/joist/issues/953, I discovered that the 'usa' images for those sims look very wrong, very tiny.  I stashed my work, and verified that I had not introduced the problem.  I ended up reverting my work, and not commiting.

For example, see the first screenshot below for CAV and 'usa'. The "kicker" is very tiny.

The 'africa' and 'africaModest' images look fine. See the second screenshot below. I'm wondering why those files are PNG, while the 'usa' files are SVG, and whether that has anything to do with this problem.

In any case, this needs to be fixed before we proceed with moving to the new approach for localized images. Assigning to the responsible devs for soccer-common with high priority.

<img width="998" alt="screenshot_3075" src="https://github.com/phetsims/soccer-common/assets/3046552/c03ea0c6-0606-4623-8cb5-393f352aeedd">

<img width="1002" alt="screenshot_3076" src="https://github.com/phetsims/soccer-common/assets/3046552/5ab629f3-d059-47cc-9d4c-443088815c40">

**Comment by pixelzoom** [comment]
I see several commits to soccer-common on Wed 3/6/24 by @amanda-phet and @Luisav1, all related to these image files.    If I checkout soccer-common prior to those commits (`git checkout 86c60a3`) then the problem goes away.  So assigning this issue to @amanda-phet and @Luisav1.

**Comment by pixelzoom** [comment]
Rather than toss all of my work... In https://github.com/phetsims/soccer-common/commit/b9dee334213c355bd5b79e72ca593cd14f7f7c7f, I went ahead and renamed the 'africa' and 'africaModest' image files, since they were not involved in the 3/6 commits.

@amanda-phet @Luisav1 please let me know when the 'usa' images are fixed, and I will renamed them by adding the 'usa' prefix.

**Comment by marlitas** [comment]
This is currently being caused because some images were migrated to svg and some are still png. @amanda-phet will be adding in the rest of the svg kicker images soon, and I imagine she can follow the new naming conventions while doing so.

**Comment by pixelzoom** [comment]
Thanks @marlitas.  I went ahead and rename the 'usa' image files in https://github.com/phetsims/soccer-common/commit/e4a8d604323d33040882cef9f82215c014e5b7dd.

**Comment by pixelzoom** [comment]
Btw...  It's a little confusing that you refer to these images as "kickers", but all of the files names are "player".     And the asserts files are kicker-artwork.ai and kicker-artwork-africa.ai.

**Comment by marlitas** [comment]
Mmm that is confusing... @amanda-phet do we want to update the names of the images to kickers? That's how they are referenced throughout the code... Feels like an easier change than refactoring all of the code to players...

**Comment by pixelzoom** [comment]
If you're going to rename filesto "kicker", I recommend doing so with a script, and using `git mv` so that git history is preserved.

**Comment by pixelzoom** [comment]
If you're going to rename files to "kicker", I recommend doing so with a bash script (see below), and using git mv so that git history is preserved.  license.json and Kicker*.ts files can quickly be updated using strings search/replace in WebStorm.

```
#!/bin/bash

# Allow patterns that match no files, so we can iterate over both .png and .svg
shopt -s nullglob

for filename in *.{png,svg}; do

  # Change 'Player' to 'Kicker'.
 NEW_FILENAME=`echo ${filename} | sed "s/Player/Kicker/g"`

 # Rename the file, preserving git history.
 git mv ${filename} ${NEW_FILENAME}
done
```

**Comment by marlitas** [comment]
I'm confused... the only files I see named `player` are image assets... you want me to preserve the git history for those? Happy to, just don't fully understand the need to do so.

**Comment by pixelzoom** [comment]
Git history is not just for code.  Why would you not preserve the git history for images?  If you wanted to verify the info in license.json, or revert to a previous verison of an image, for example.   

And speaking of license.json, I've noticed that most of the dates in license.json appear to be incorrect for soccer-common. For example, every entry in images/africa/license.json is `Copyright 2022`, but none of the image in images/africa/ existed until 8/30/2023

**Comment by marlitas** [comment]
Reverting to a previous version of an image, doesn't seem like something that I would want to do, since I would hope it matches the assets file as much as possible, however I see your reasoning and will make sure that the git history is preserved in the renames.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/soccer-common/commit/ee8ac8ff15c9d7b3bd57274fdae7a763407551fd, image files were rename from "Player" to "Kicker".  

Slack:

@pixelzoom 
> Do you want me to change “player” => “kicker” in soccer-common?

@amanda-phet 
> I can go either way with player/kicker

@pixelzoom 
> The asset files are kicker, the code is kicker…. and the images files are player.

@amanda-phet 
> Right, I saw the issue, and I’m fine with renaming those now or later it doesn’t matter to me

**Comment by pixelzoom** [comment]
In order to proceed with conversion to the new Region and Culture approach, so I can address https://github.com/phetsims/center-and-variability/issues/615 (migration rules)...

In the above commits, I integrated new SVG files for africa and africaModest, provided by @amanda-phet.    The screenshots below were provided by @amanda-phet, and show how some of the kicker numbers map to images for other regions.

After making these changes, the original problem was not fixed. And now the kickers for _all_ regions are tiny.


africa:
![africa](https://github.com/phetsims/soccer-common/assets/3046552/1500e875-cef7-4b4d-8326-f64789dd1c13)

africaModest:
![africaModest](https://github.com/phetsims/soccer-common/assets/3046552/0058f2b6-4772-4488-a348-0056eefbb194)

**Comment by pixelzoom** [comment]
> After making these changes, the original problem was not fixed. And now the kickers for _all_ regions are tiny.

It looks like this constant in KickerNode.ts was the culprit:

```ts
const SCALE = 0.31;
```

Using the published version (1.1.5) as a reference, I changed this value to `0.645`. 

@marlitas please review. Close if OK.

**Comment by pixelzoom** [comment]
In KickerNode.ts, I also see this comment.  Should this be addressed?

```ts
      // Avoid a flickering on firefox where the image temporarily disappears (even in built mode)
      // TODO: once svg images are in, remove webgl flag and send to QA, https://github.com/phetsims/soccer-common/issues/11
      renderer: 'webgl',
```

**Comment by amanda-phet** [comment]
The kickers still looks small to me on main. We knew why they were small, but @Luisav1 did what you did and when the images were full sized they looked blurry (which shouldn't happen with an SVG!). We decided that after all the SVGs were in we would remove `webgl` and see if they looked better and no longer had an issue in firefox.

**Comment by pixelzoom** [comment]
> The kickers still looks small to me on main. 

Here's production, https://phet.colorado.edu/sims/html/center-and-variability/latest/center-and-variability_all.html?debugger:

<img width="1119" alt="screenshot_3080" src="https://github.com/phetsims/soccer-common/assets/3046552/0f9cedc3-7a3b-44f2-bdb7-8f09cf3b6f13">

Here's main:

<img width="1119" alt="screenshot_3079" src="https://github.com/phetsims/soccer-common/assets/3046552/cd31c240-7241-472a-9721-1ea748d1ea25">

**Comment by marlitas** [comment]
Yes the bug was a combination of consistent image sizes and then updating the constant once that was done and we knew what the new dimensions would be. I should have been more specific. Thanks @pixelzoom. 

Kicker sizes look good on main to me! Thanks.

I'll go ahead an finish up the `webgl` renderer questions in this issue: https://github.com/phetsims/soccer-common/issues/11

Thanks all!
