### ISSUE TITLE
Use group-based grab/drag interaction for soccer balls

### ISSUE THREAD

**Issue by marlitas** [phetsims/soccer-common#2]
We have decided that this is not necessary for CaV, but would like to implement an updated GrabDragInteraction ( https://github.com/phetsims/scenery-phet/issues/815 ) for the soccer balls in this repo for future use in sims such as Mean: Share and Balance. 

This is not blocking CaV, but will be a priority for MSaB when it is scheduled and development begins. This will crossover with @zepumph or @jessegreenberg's work in https://github.com/phetsims/scenery-phet/issues/815

**Comment by zepumph** [comment]
Some notes about CAV's specific implemnetation:

* Highlights are drawn custom by the sim, perhaps we want to try to use scenery a bit more to support interactive highlights + PDOM focus
* Listbox as a motivating design for the keyboard interaction: https://github.com/phetsims/center-and-variability/issues/351#issuecomment-1646118127 (not sure if that would work well for 2d selection though).

**Comment by zepumph** [comment]
Work for this issue will most likely be done in https://github.com/phetsims/scenery-phet/issues/815

**Comment by zepumph** [comment]
GroupSortInteractionModel and GroupSortInteractionView now live in scenery-phet, and are being used for the soccer ball scene interaction in soccer-common. I would recommend to close this issue. Though not all work is done with this work, soccer-common is central to it, and will be completed over in  https://github.com/phetsims/scenery-phet/issues/815. Please also see https://github.com/phetsims/mean-share-and-balance/issues/137 for work in that sim (which will also include a soccer ball group sort).
